# Utiliza una imagen base de Node.js
FROM node:18-alpine

# Establece el directorio de trabajo en la imagen
WORKDIR /app/frontend

# Copia los archivos de package.json y package-lock.json a la imagen
COPY package*.json ./

# Instala las dependencias del proyecto
RUN npm install

# Copia el resto de los archivos del frontend a la imagen
COPY . .

# Expone el puerto en el que se ejecutará el frontend
EXPOSE 5173

# Define el comando para iniciar el frontend
CMD ["npm", "run", "dev"]