services:
  backend:
    container_name: apv_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    #volumes: 
    # - ./backend:/app/backend # Montamos el backend en /workspace/backend
    ports:
      - "3000:3000" 
    depends_on:
      - database
    environment:
      - NODE_ENV=development
    env_file:
    - ./backend/.env
    networks:
      - apv_network

  frontend:
    container_name: apv_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    #volumes:
    # - ./frontend:/app/frontend # Montamos el frontend en /workspace/frontend
    ports:
      - "5000:5000"
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
    env_file:
      - ./frontend/.env
    networks:
      - apv_network

  database:
    container_name: apv_mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - apv_network

volumes:
  mongo-data:
    name: mongo-data

networks:
  apv_network:
    name: apv_network
    driver: bridge