# Utiliza una imagen base de Node.js
FROM node:16-alpine

# Establece el directorio de trabajo en la imagen
WORKDIR /app/backend

# Copia los archivos de package.json y package-lock.json a la imagen
COPY package*.json ./

# Instala las dependencias del proyecto
RUN npm install

# Copia el resto de los archivos del backend a la imagen
COPY . .

# Expone el puerto en el que se ejecutará el backend
EXPOSE 3000

# Define el comando para iniciar el backend
CMD [ "npm", "start" ]